### ISSUE TITLE
What components do I have to install before I can use this script

### ISSUE THREAD

**Issue by MajorAdam** [typhoon-hil/LibreOfficeToPDF#5]
I have installed uno use pip,but it gets this"importError: cannot import name 'Element' from 'base' ".
Thank you for your time

**Comment by Sup3rGeo** [comment]
Hi!

You don't need to install anything else - just install LibreOffice and run the LibreOfficeToPDF binary.
No need to install uno or anything else using pip.

Can you explain step-by-step what you are doing?

**Comment by MajorAdam** [comment]
1.install LibreOffice
2.download LibreOfficeToPDF
3.add LibreOfficeToPDF to path
4.when I use the script, it gets "importError: cannot import uno";then I pip install uno,  and it gets "importError: cannot import name 'Element' from 'base' "

**Comment by MajorAdam** [comment]
I think there are environment differences. I don't have soffice command and python uno module doesn't come along with system(centos 6.9)

**Comment by MajorAdam** [comment]
I have found soffice and add it to path.It still gets "ModuleNotFoundError: No module named 'uno'".I think I need to yum install something like python-uno?

**Comment by MajorAdam** [comment]
I have solved this problem. I used my own python ,but I found there is a python in libreoffice/program directory.After I change to that python, everything is OK. Again , thank you for your time.You are really helpful. I will close this issue.
